spring:
  application:
    name: "configserver"
  profiles:
    # active: native              # refers to the configuration where set up to use the file system or classpath as its configuration source
    active: git                   # refers to the configuration where Spring Cloud Config Server is set up to fetch configuration properties from a remote Git repository
  cloud:
    config:
      server:
        #native:
        #search-locations: "classpath:/config"  #Reading configuration from class path location of Config Server
        #search-location: " "file:///C://......." #Reading configuration from file System location
        git:
          uri: "https://github.com/kaushal000125/bankAppConfig.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"